Repository minos-framework/minos-api-gateway, pull requests merged in 2021-06, with the labels that each got.

#18 First documentation - issue #17
  .gitattributes
  .gitignore
  .pre-commit-config.yaml
  AUTHORS.md
  CONTRIBUTING.md
  Makefile
  README.md
  RUNTHETESTS.md
  SETUP.md
  docs/api/modules.rst
  docs/authors.rst
  docs/conf.py
  docs/history.rst
  docs/index.rst
  docs/readme.rst
  docs/runthetests.rst
  poetry.lock
  pyproject.toml
Labels: documentation

#22 Update minos-apigateway-common dependency and Replace static discover…
  minos/api_gateway/rest/coordinator.py
  poetry.lock
  pyproject.toml
  tests/test_config.yml
Labels: enhancement

#24 Add Typer CLI
  minos/api_gateway/rest/__init__.py
  minos/api_gateway/rest/cli.py
  minos/api_gateway/rest/launchers.py
  poetry.lock
  pyproject.toml
  setup.cfg
  tests/config.yml
  tests/test_api_gateway/test_rest/test_cli.py
  tests/test_api_gateway/test_rest/test_coordinator.py
  tests/test_api_gateway/test_rest/test_service.py
  tests/utils.py
Labels: enhancement

#27 Redirect path BUG and improvement of tests
  minos/api_gateway/rest/coordinator.py
  poetry.lock
  pyproject.toml
  tests/config.yml
  tests/handlers.py
  tests/mock_servers/server.py
  tests/test_api_gateway/test_rest/test_coordinator.py
  tests/test_api_gateway/test_rest/test_service.py
Labels: bug

#32 #31 (Improve the way to retrieve the response from the microservice)
  minos/api_gateway/rest/coordinator.py
Labels: enhancement

#36 #35 (Improve how `discovery` errors are handled)
  minos/api_gateway/rest/coordinator.py
  tests/config.yml
  tests/test_api_gateway/test_rest/test_coordinator.py
Labels: bug

#34 #33 (add `__main__` module)
  minos/api_gateway/rest/__main__.py
  minos/api_gateway/rest/coordinator.py
  tests/config.yml
  tests/test_api_gateway/test_rest/test_coordinator.py
Labels: enhancement

#38 #37 (url path with parts bug extracting microservice name)
  minos/api_gateway/rest/coordinator.py
  tests/test_api_gateway/test_rest/test_coordinator.py
Labels: bug
