Repository minos-framework/minos-api-gateway, pull requests merged in 2022-02, with the labels that each got.

#76 Admin Section
  .github/workflows/python-tests.yml
  api_gateway.db
  identifier.sqlite
  minos/api_gateway/rest/backend/admin/3rdpartylicenses.txt
  minos/api_gateway/rest/backend/admin/assets/images/minos_color@2x.png
  minos/api_gateway/rest/backend/admin/color.dae87a04d07ca92b.png
  minos/api_gateway/rest/backend/admin/favicon.ico
  minos/api_gateway/rest/backend/admin/hue.8b1818380241e6ac.png
  minos/api_gateway/rest/backend/admin/main.0d2304017c562996.js
  minos/api_gateway/rest/backend/admin/polyfills.cacc82dae5605706.js
  minos/api_gateway/rest/backend/admin/primeicons.29151a741d66863a.woff
  minos/api_gateway/rest/backend/admin/primeicons.5f5d08cd089b4e5d.ttf
  minos/api_gateway/rest/backend/admin/primeicons.76044b1c189cc4d7.svg
  minos/api_gateway/rest/backend/admin/primeicons.964f445f3ea9db80.eot
  minos/api_gateway/rest/backend/admin/runtime.3586ab90ea013581.js
  minos/api_gateway/rest/backend/admin/styles.ee7401a7ef5a34ac.css
  minos/api_gateway/rest/backend/templates/index.html
  minos/api_gateway/rest/config.py
  minos/api_gateway/rest/database/models.py
  minos/api_gateway/rest/database/repository.py
  minos/api_gateway/rest/handler.py
  minos/api_gateway/rest/service.py
  minos/api_gateway/rest/urlmatch/authmatch.py
  poetry.lock
  postman/API Gateway.postman_collection.json
  pyproject.toml
  tests/config-auth-disabled.yml
  tests/config.yml
  tests/config_without_auth.yml
  tests/test_api_gateway/test_rest/test_admin.py
  tests/test_api_gateway/test_rest/test_authentication.py
  tests/test_api_gateway/test_rest/test_config.py
Labels: enhancement

#86 #84 - Bug getting Admin Index page
  minos/api_gateway/rest/service.py
Labels: bug

#87 #85 - Review Auth default routes
  HISTORY.md
  minos/api_gateway/rest/__init__.py
  minos/api_gateway/rest/handler.py
  minos/api_gateway/rest/service.py
  pyproject.toml
  tests/config.yml
  tests/test_api_gateway/test_rest/test_authentication.py
Labels: enhancement

#88 0.3.0
  HISTORY.md
  minos/api_gateway/rest/__init__.py
  minos/api_gateway/rest/handler.py
  minos/api_gateway/rest/service.py
  pyproject.toml
  tests/config.yml
  tests/test_api_gateway/test_rest/test_authentication.py
Labels: release

#90 #89 - Admin index file BUG
  HISTORY.md
  minos/api_gateway/rest/__init__.py
  minos/api_gateway/rest/backend/admin/main.0d2304017c562996.js
  minos/api_gateway/rest/backend/admin/main.727c29f160d3bc80.js
  minos/api_gateway/rest/backend/templates/index.html
  minos/api_gateway/rest/service.py
  pyproject.toml
Labels: bug

#91 0.3.1
  HISTORY.md
  minos/api_gateway/rest/__init__.py
  minos/api_gateway/rest/backend/admin/main.0d2304017c562996.js
  minos/api_gateway/rest/backend/admin/main.727c29f160d3bc80.js
  minos/api_gateway/rest/backend/templates/index.html
  minos/api_gateway/rest/service.py
  pyproject.toml
Labels: release

#93 #92 - Authorization
  minos/api_gateway/rest/backend/admin/main.0d2304017c562996.js
  minos/api_gateway/rest/backend/admin/main.33051811e0a291cf.js
  minos/api_gateway/rest/backend/templates/index.html
  minos/api_gateway/rest/database/models.py
  minos/api_gateway/rest/database/repository.py
  minos/api_gateway/rest/handler.py
  minos/api_gateway/rest/service.py
  minos/api_gateway/rest/urlmatch/autzmatch.py
  tests/test_api_gateway/test_rest/test_admin.py
  tests/test_api_gateway/test_rest/test_authorization.py
Labels: enhancement

#94 v0.4.0
  HISTORY.md
  minos/api_gateway/rest/__init__.py
  minos/api_gateway/rest/backend/admin/main.33051811e0a291cf.js
  minos/api_gateway/rest/backend/templates/index.html
  minos/api_gateway/rest/database/models.py
  minos/api_gateway/rest/database/repository.py
  minos/api_gateway/rest/handler.py
  minos/api_gateway/rest/service.py
  minos/api_gateway/rest/urlmatch/autzmatch.py
  pyproject.toml
  tests/test_api_gateway/test_rest/test_admin.py
  tests/test_api_gateway/test_rest/test_authorization.py
Labels: enhancement
